 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  ktvic_caption: # name of the dataset builder
    # dataset_card:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /kaggle/input/ktvic-dataset/ktvic_dataset/train_data.json
          storage: /kaggle/working/ktvic_dataset/annotations/train_data.json
        val:
          url: /kaggle/input/ktvic-dataset/ktvic_dataset/test_data.json
          storage: /kaggle/working/ktvic_dataset/annotations/test_data.json
        test:
          url: /kaggle/input/ktvic-dataset/ktvic_dataset/test_data.json
          storage: /kaggle/working/ktvic_dataset/annotations/test_data.json
      images:
        storage: /kaggle/input/ktvic_dataset/train-images

    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
      eval:
        name: "blip2_image_eval"
        image_size: 224
