 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  ktvic_caption: # name of the dataset builder
    # dataset_card:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /kaggle/input/ktvic-cocoform/ktvic2coco/train_captions.json
          storage: /kaggle/working/ktvic2coco/annotations/train_captions.json
        val:
          url: /kaggle/input/ktvic-cocoform/ktvic2coco/val_captions.json
          storage: /kaggle/working/ktvic2coco/annotations/val_captions.json
        test:
          url: /kaggle/input/ktvic-cocoform/ktvic2coco/test_captions.json
          storage: /kaggle/working/ktvic2coco/annotations/test_captions.json
      images:
        storage: /kaggle/input/ktvic-cocoform/ktvic2coco

    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
      eval:
        name: "blip2_image_eval"
        image_size: 224
