 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  ktvic_caption: # name of the dataset builder
    # dataset_card:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/ktvic_train.json
          storage: ktvic/annotations/ktvic_train.json
        val:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/ktvic_val.json
          storage:  ktvic/annotations/ktvic_val.json
        test:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/ktvic_test.json
          storage: ktvic/annotations/ktvic_test.json
      images:
        storage: ktvic/images/
