 # Copyright (c) 2023, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  ktvic_caption_instruct: # name of the dataset builder
    # dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    vis_processor:
      train:
        name: "clip_image_train"
        image_size: 224
      eval:
        name: "clip_image_eval"
        image_size: 224

    text_processor:
        train:
          name: blip_instruction
          modality: image
          task: caption
        eval:
          name: blip_caption

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /content/data/ktvic2coco/train_captions.json
          storage: /content/data/ktvic2coco/annotations/train_captions.json
        val:
          url: /content/data/ktvic2coco/val_captions.json
          storage: /content/data/ktvic2coco/annotations/val_captions.json
        test:
          url: /content/data/ktvic2coco/test_captions.json
          storage: /content/data/ktvic2coco/annotations/test_captions.json
      images:
        storage: /content/data/ktvic2coco
